# Generated by Django 5.2.1 on 2025-05-13 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('games_collected', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'collection_log',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.CharField(max_length=20)),
                ('draw_time', models.TimeField(blank=True, null=True)),
                ('numbers', models.CharField(max_length=255)),
                ('jackpot', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('next_draw_date', models.CharField(blank=True, max_length=20, null=True)),
                ('next_draw_time', models.TimeField(blank=True, null=True)),
                ('next_jackpot', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lotterydata.game')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotterydata.state')),
            ],
            options={
                'db_table': 'game_results',
            },
        ),
        migrations.CreateModel(
            name='StateGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotterydata.game')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotterydata.state')),
            ],
            options={
                'db_table': 'state_games',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='states',
            field=models.ManyToManyField(through='lotterydata.StateGame', to='lotterydata.state'),
        ),
    ]
